name: personal-website2
recipe: mean
excludes:
  - node_modules
config:
  port: '3000'
services:
  appserver:
    run:
      - npm run start:dev
    extras:
      - "wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh"
tooling:
  heroku:
    service: appserver
    cmd: /usr/bin/heroku