# fly.toml app configuration file generated for resume-nuflrq on 2025-04-25T12:49:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resume-nuflrq'
primary_region = 'fra'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[build]
  dockerfile = 'Dockerfile'