services:
  # A Node.js web service
  - type: web
    name: personal-website
    env: node
    repo: https://github.com/giacomo-secchi/resume
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    domains:
      - resume.giacomosecchi.com